### ISSUE TITLE
Bundling a different language

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-build-classic#11]
By default, English strings are used in the bundles. We can make it configurable by specifying the language in `build-config.js` and reading it from Webpack config files.

**Comment by Reinmar** [comment]
An example of using our Webpack plugin is here: https://github.com/ckeditor/ckeditor5-labs/tree/master/integrations/webpack-localization

**Comment by pomek** [comment]
A lot of translation' files are missing:

![image](https://user-images.githubusercontent.com/2270764/29165963-eaa97e80-7dc4-11e7-956e-df59d228d7bf.png)

**Comment by Reinmar** [comment]
Maybe true right now since we haven't regenerated them for a long time. I'll do it today.

**Comment by pomek** [comment]
But it works :D 

![image](https://user-images.githubusercontent.com/2270764/29166070-4f55f7dc-7dc5-11e7-9854-a8c973894e76.png)

**Comment by pomek** [comment]
The question is – should we add the `CKEditorWebpackPlugin` every time or only if the specified language is other than `en`?

**Comment by Reinmar** [comment]
I think all the time. To KISS and to make sure that the translations (even en->en) are used.

**Comment by Reinmar** [comment]
I can't upload the translations for now: https://github.com/ckeditor/ckeditor5-dev/issues/249.
