### ISSUE TITLE
Deploying ckeditor5 classic build to a Staging Server does not work in Meteor

### ISSUE THREAD

**Issue by formspoint** [ckeditor/ckeditor5-build-classic#35]
I installed the classic build like so:

```javascript
meteor npm install --save @ckeditor/ckeditor5-build-classic
```

and my package.json file has the dependency list:

```json
  "dependencies": {
    "@ckeditor/ckeditor5-build-classic": "^1.0.0-alpha.2",
```

I import and use the classic editor like this:

```javascript
import ClassicEditor from '@ckeditor/ckeditor5-build-classic/build/ckeditor';
```

everything works locally, but when I deploy, unlike the other packages in my project, the only thing that renders is the textarea tag and not the actual ckeditor5 lib.

Any I should check on?

**Comment by Reinmar** [comment]
There are many things that might be broken when you deploy your code, but few of those things have anything to do with the editor. It's therefore hard for me to help you. There's a huge chance that the problem is not the editor but something about your deploy process.

Anyway, check the JS console, make sure you cleared the cache, check whether something at all happened. The editor, if tried to initialize, would throw an error if something didn't work. So you'll either see an error on the console or, if there won't be any error, you'll kinda know that your app didn't even try to initialise the editor.

**Comment by formspoint** [comment]
UPDATE:

UPDATE:

I put more debugging in, it never gets to the ```console.log('!! EDITOR: ', editor);``` line, but does log the ```console.log('## Sub Ready');``` line.  Basically it crashes when trying to use ClassicEditor.  I think the editor is not defined for some reason.  Does the editor have any special Node.js requirements or lib requirements? 

Lots more console logs:
```javascript
Template.testTemplate.onRendered(function() {
	this.autorun(() => {
		console.log('&& inside Autorun');
		if (this.subscriptionsReady()) {
			console.log('## Sub Ready');
			ClassicEditor.create( document.querySelector( '#noteContent' ) )
				.then( editor => {
					console.log('!! EDITOR: ', editor);
					let template = this;
					editor.document.on('changesDone', () => {
						console.log('** EDITOR: ', editor);
					  template.state.set('note', editor.getData() );
					});
					let act = accounts.findOne({ userId: Session.get('accountId') });
					let note = act && act.accountNote || '';
					console.log('@@ NOTE: ', note);
					editor.setData(note);
				})
				.catch( error => {
					console.error( error.stack );
				});
			}
	});
});

```

**Comment by Reinmar** [comment]
> Basically it crashes when trying to use ClassicEditor.

But how does it crash? The most important thing and the first thing to report is usually the steps (which you partially done) and the stack trace. The latter is still missing ;)

**Comment by formspoint** [comment]
Thanks.

The steps to reproduce are:

I installed the classic build like so:

```javascript
meteor npm install --save @ckeditor/ckeditor5-build-classic
```

and my package.json file has the dependency list:

```json
  "dependencies": {
    "@ckeditor/ckeditor5-build-classic": "^1.0.0-alpha.2",
```

I import and use the classic editor like this:

```javascript
import ClassicEditor from '@ckeditor/ckeditor5-build-classic/build/ckeditor';
```

Added the code to create the Classic Editor in my onRendered method for the Blaze template:

```javascript
Template.testTemplate.onRendered(function() {
	this.autorun(() => {
		console.log('&& inside Autorun');
		if (this.subscriptionsReady()) {
			console.log('## Sub Ready');
			ClassicEditor.create( document.querySelector( '#noteContent' ) )
				.then( editor => {
					console.log('!! EDITOR: ', editor);
					let template = this;
					editor.document.on('changesDone', () => {
					   console.log('** EDITOR: ', editor);
					   template.state.set('note', editor.getData() );
					});
					let act = accounts.findOne({ userId: Session.get('accountId') });
					let note = act && act.accountNote || '';
					console.log('@@ NOTE: ', note);
					editor.setData(note);
				})
				.catch( error => {
					console.error( error.stack );
				});
			}
	});
});
```

Added code to the template for the Editor
```html
<textarea id="noteContent" name="content">{{note}}</textarea>
```

Run it locally and the Editor works/renders fine.

Then deploy to my staging server and it never renders -- just the textarea.  I look in the console and the following error is logged in the console... 

Note: the code has been minified -- and I do not have source maps (Meteor doesn't have that feature yet).

I said it crashes, well, really it just throws and a Reference Error and the exception is caught in the ClassicEditor's .catch.

The exception is the one I posted above (but will repost here).

```javascript
ReferenceError: GN is not defined
    at then (https://test.staging.com/ea8cca2b5c78d764c7853199cbb58e04333db933.js?meteor_js_resource=true:13:247730)
    at https://test.staging.com/ea8cca2b5c78d764c7853199cbb58e04333db933.js?meteor_js_resource=true:3:7389
    at <anonymous>
```

I believe the reason for the cryptic name GN is due to the minification of the code.

**Comment by Reinmar** [comment]
Could you disable minification or enable source maps? It's hard to tell anything based on a minified stack trace.

**Comment by formspoint** [comment]
Thanks.  I’ll look into deploying without minification. If I chant get around this, what are our alternatives?

**Comment by Reinmar** [comment]
Checking this with a debugger on a minified source. But we won't be able to help you. We can neither see the bug nor debug it, so taken that the entire infrastructure of Meteor is involved, we have no ability to guess what might went wrong.

**Comment by Mgsy** [comment]
I'm closing it due to a lack of activity.
