### ISSUE TITLE
Pulling in the theme

### ISSUE THREAD

**Issue by carltoncolter** [ckeditor/ckeditor5-build-classic#41]
For some reason when I use the build, it doesn't pull in the theme correctly or something strange is happening where the styles are not coming over, then I get the strange layout below.  While my code is submitted to GitHub, I don't want you to have to go through it, if you can point me in the right direction, I'd greatly check it myself.

**Comment by carltoncolter** [comment]
![image](https://user-images.githubusercontent.com/25727192/37550761-2c546f98-2969-11e8-81cf-8c3810d75e1f.png)

**Comment by Reinmar** [comment]
I assume you customised and rebuilt one of the existing buids, yes? Could you post your `webpack.config.js` and all the things that you changed? And... npm version just to be sure.

**Comment by Reinmar** [comment]
Potential DUP in https://github.com/ckeditor/ckeditor5-build-balloon/issues/15. 

cc @oleq – I'm afraid that the style builder has some problems.

**Comment by gauravjain028** [comment]
@Reinmar 
I tried with Classic editor build, it is working for me, but Balloon editor is not working for me. I tried with default webpack.config.js

**Comment by Reinmar** [comment]
I can't think of any difference between these two builds which could matter here :|. Could you paste here exactly what commands you executed and in what order?

**Comment by gauravjain028** [comment]
1. I downloaded as Zip.
2. Run command `npm install`
3. Run command `npm run build`
4. opened the `sample/index.html` in browser.

**Comment by Reinmar** [comment]
What did you download? The release from here?

![image](https://user-images.githubusercontent.com/156149/37595103-c49a3f20-2b77-11e8-8bd7-e6f37518b128.png)

**Comment by gauravjain028** [comment]
I download it from stable branch but I tried from Release section as well and found same problem.

**Comment by AnnaTomanek** [comment]
It's the same for me, when trying to build the docs (`npm run docs`) on the `stable` branch.

I cloned the `ckeditor5` repository fresh.
I followed the steps from the [Development environment](https://docs.ckeditor.com/ckeditor5/latest/framework/guides/contributing/development-environment.html#setting-up-the-ckeditor-development-environment) guide.
Also tried `lerna clean` and `lerna bootstrap`.

All snippets from Examples and Features look the same.
![screen shot 2018-03-19 at 14 16 57](https://user-images.githubusercontent.com/538321/37599259-990819b0-2b84-11e8-9b77-3c8ce43416fc.png)

No errors returned when building.
No errors in the console.

**Comment by carltoncolter** [comment]
Here is my [repository with all of my changes](https://github.com/carltoncolter/ckeditor5-dynamics365) with all of the changes, etc.  I started to make it so that you could use CKEditor5 as a custom control in Dynamics CRM 365 to enable html editing of a field.

My npm version is 3.10.10
My nodejs version is 6.11.2
I am using Visual Studio Code.  I changed the project.json to run webpack directly instead of a bash script.

The only changes I made for ckeditor was that I added the fontSize and fontFamily plugins...  

Here is my [webpack config file](https://github.com/carltoncolter/ckeditor5-dynamics365/blob/master/webpack.config.js).

I'd love to help figure out what is going on here, but being new to webpack, I'm not sure where to begin.

**Comment by carltoncolter** [comment]
The bug is in the devutils, themeimporter.js  It is doing a name match on ckeditor5- in getPackageName

There are a lot fo ways to resolve this...  currently the match is:

`const match = inputFilePath.match( /ckeditor5-[^\\/]+/ );`

I changed mine to:

`const match = inputFilePath.match( /@ckeditor\/ckeditor5-[^\\/]+/ig );`

This does two things, one, it ensures I'm getting the last ckeditor5- match and usingthe @ckeditor ensures I'm not matching my project name which also starts with ckeditor5-.

**Comment by carltoncolter** [comment]
You could just use: `const match = inputFilePath.match( /ckeditor5-[^\\/]+/ig );`  That would fix it too and may be more flexible for the other dev areas...

**Comment by carltoncolter** [comment]
This is what I now see after the change:
![image](https://user-images.githubusercontent.com/25727192/37621848-8e827104-2b96-11e8-9ab7-be97d78beed6.png)

**Comment by carltoncolter** [comment]
Created a pull request for ckeditor5-dev that makes the change to resolve the issue.

**Comment by AnnaTomanek** [comment]
Changing the folder name from `ckeditor5-workspace\ckeditor5` to `cke5-workspace\ckeditor5` fixed the issue for me. Thanks!

**Comment by oleq** [comment]
Just FYI:

The name of the package in the algorithm is necessary for 2 reasons:
1. Developers can use a custom entry point JS file passed to Webpack. They can include their own CSS imports the, unrelated to CKE5. To make sure our theme importer does **not** process those imports, we must check if the CSS file it is about process belongs to some CKE5 package (ckeditor5-*).
2. The package name is used to determine the location of the theme file in the theme. For instance, if the loader starts processing the 
```
/Users/oleq/Sites/cke5/ckeditor5-build-balloon-1.0.0-beta.1/node_modules/@ckeditor/ckeditor5-link/theme/linkform.css
``` 
file, it should determine the package name as `ckeditor5-link` and then use it to load the related theme file, which is 
```
/Users/oleq/Sites/cke5/ckeditor5-build-balloon-1.0.0-beta.1/node_modules/@ckeditor/ckeditor5-theme-lark/theme/ckeditor5-link/linkform.css
```
which in fact corresponds to the following pattern:

```
<ThemeImporterOptions#themePath>/theme/<package-name>/<the rest of the path>
```

**Comment by Reinmar** [comment]
It should be fixed now (see https://github.com/ckeditor/ckeditor5-dev/pull/386). I released a new version of `@ckeditor/ckeditor5-dev-utils` so the fix should be already available for you.
