### ISSUE TITLE
Add Alignment feature to the editor

### ISSUE THREAD

**Issue by m4noj** [ckeditor/ckeditor5-build-classic#62]
## add alignment feature plugin to the editor.
 here's a pull request : #61

**Comment by oleq** [comment]
We're aware that none of the editor builds ships with all the available features (plugins). But we did it on purpose. 

The idea behind this particular build is to keep it simple and, most of all, semantic content–oriented. The alignment feature is about visual formatting, not about the content semantics so it does not belong in this build.

If you need a build-classic with the alignment feature, you can [add it on your own](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html). You can also use the [document editor build](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/overview.html#document-editor) which has the plugin out–of–the–box.

**Comment by dbramwell** [comment]
@m4noj I think this is worthwhile, possibly as another package. I think text justification is an important part of a text editor as far as I can see there is no way for me to add the alignment plugin to me React app without ejecting from Create React App and messing with webpack. Any chance you could release your branch in NPM?

**Comment by oleq** [comment]
@dbramwell You can fork this build, modify it (imports, config), build, then push to your GH and reference in your project.
