### ISSUE TITLE
Input Chinese Style Lost

### ISSUE THREAD

**Issue by imyyg** [ckeditor/ckeditor5-build-classic#69]
设置样式不支持中文输入，已在官方示例中重现问题，例如点击加粗，输入英文字体正常加粗，在输入法中输入中文确认后没有加粗样式，其他斜体，字体大小等问题一样。 @Reinmar #66

**Comment by Mgsy** [comment]
Hello, could you edit your issue and translate your message to english?

**Comment by imyyg** [comment]
Setting style does not support Chinese input, which has been reproduced in official examples, such as click bold, input English font normal bold, input Chinese confirmation in the input method after no bold style, other italics, font size and other issues are the same.

**Comment by imyyg** [comment]
There is no such problem in the official ckeditor4 example

**Comment by Mgsy** [comment]
Thanks for the report. Unfortunately, composition in CKEditor 5 has some issues and we're still working on it. 

However, I can't find this issue reported, so I'll close it as a duplicate and move it to the proper repository - https://github.com/ckeditor/ckeditor5-typing/issues/188.

**Comment by imyyg** [comment]
Sorry, I don't quite understand what you mean, is that you can't reproduce this problem?@Mgsy

**Comment by Mgsy** [comment]
>Sorry, I don't quite understand what you mean, is that you can't reproduce this problem?@Mgsy

I'm able to reproduce it and your issue is valid. I've just moved it to the repository in which we track all problems related to handling composition.

**Comment by imyyg** [comment]
OK，thank you
