### ISSUE TITLE
copy from word with other Software

### ISSUE THREAD

**Issue by zhyit** [ckeditor/ckeditor5-build-classic#79]
I tried using Keckeditor ecosystem documentation
Demonstration edit box, but failed. I use WPS software, but the content copied in this software can not be copied to the editor, I hope to support various word software.

**Comment by Mgsy** [comment]
We have already confirmed a feature request for WPS support. You can find it here - https://github.com/ckeditor/ckeditor5-paste-from-office/issues/58.
