### ISSUE TITLE
Consider switching to Rollup

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-build-classic#8]
We've been using Rollup initially because it gives smaller builds and had ES6 modules support out of the box, but we had to stop using it because of https://github.com/rollup/rollup-plugin-node-resolve/issues/67.

That issue is resolved now and we can again check if Rollup wouldn't be better. The things to verify will be the stability of integration with Babili (with sourcemaps – I know there were issues) and what are the options to bundling in or extracting and minifying CSS.

Also, https://medium.com/webpack/webpack-and-rollup-the-same-but-different-a41ad427058c

**Comment by Reinmar** [comment]
Interesting results from [React's world](https://facebook.github.io/react/blog/2017/09/26/react-v16.0.html#reduced-file-size):

> Despite all these additions, React 16 is actually smaller compared to 15.6.1!
> 
> * react is 5.3 kb (2.2 kb gzipped), down from 20.7 kb (6.9 kb gzipped).
> * react-dom is 103.7 kb (32.6 kb gzipped), down from 141 kb (42.9 kb gzipped).
> * react + react-dom is 109 kb (34.8 kb gzipped), down from 161.7 kb (49.8 kb gzipped).
> * That amounts to a combined 32% size decrease compared to the previous version (30% post-gzip).
>
> The size difference is partly attributable to a change in packaging. React now uses Rollup to create flat bundles for each of its different target formats, resulting in both size and runtime performance wins. The flat bundle format also means that React's impact on bundle size is roughly consistent regardless of how you ship your app, whether it's with Webpack, Browserify, the pre-built UMD bundles, or any other system.

**Comment by fredck** [comment]
Wow... impressive numbers. If we are supposed to have similar results, we should strongly consider doing this move earlier than later.

**Comment by Reinmar** [comment]
I don't think that we'll be able to save that much, but even 10% size decrease would be worth the time.

**Comment by Reinmar** [comment]
I don't think that we'll do this change. Having builds based on webpack gives us the most common environment. Also, our plugins required to build the editor's translations are only available for webpack for now.
